### PR TITLE
Fix jupyter_server version req

### PR DESCRIPTION
**Pull request by vikramaditya91**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

See this for why we need it:
https://github.com/jupyter-server/jupyter-resource-usage/issues/169

### CODE REVIEW

**Comment by vikramaditya91** [comment]
Hmm. [CircleCI seems operational atm](https://status.circleci.com/)

Wonder if it has to do with a secret that I would need access to?

**Comment by jtpio** [comment]
Thanks @vikramaditya91.

Indeed the CircleCI failure looks odd. We can try a re-render just to be sure.

**Comment by jtpio** [comment]
@conda-forge-admin, please rerender

**Comment by jtpio** [comment]
Tried kicking CI to see if the issues were resolved.

**Comment by vikramaditya91** [comment]
> you may have revoked the CircleCI OAuth app.

@jtpio If you have access to the CircleCI, could you please try [this](https://support.circleci.com/hc/en-us/articles/360051228052-How-to-Perform-a-Re-Authentication)

**Comment by jtpio** [comment]
I think this is managed by the `conda-forge` infrastructure. Not sure what to do because I don't have access to CircleCI.

**Comment by jtpio** [comment]
@conda-forge-admin, please rerender

**Comment by vikramaditya91** [comment]
@conda-forge/core 
Could you please help us figure out what is wrong with the CircleCI check

**Comment by jtpio** [comment]
Looks like the CI passed in https://github.com/conda-forge/jupyter-resource-usage-feedstock/pull/9 when updating to 0.7.1.

I incorporated the `jupyter_server` change there, thanks again @vikramaditya91!

**Pull request closed without merging**
